/*
    The question is generated by OpenAI GPT-4o

    Sorting with Structs
    Using the Student struct:
    Store details of 5 students in an array.
    Sort the students by their roll number in ascending order.
    Display the sorted list.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct Student
{
    int rollNo;
    char name[50];
};

void clearInputBuffer()
{
    int c;
    while ((c = getchar()) != '\n' && c != EOF)
        ;
}

void sortStudents(struct Student *stud, size_t size)
{
    struct Student temp;
    // Basic bubble sort.
    for (int i = 0; i < size; i++)
    {
        for (int j = 0; j < size - 1; j++)
        {
            if (stud[j].rollNo > stud[j + 1].rollNo)
            {
                temp = stud[j];
                stud[j] = stud[j + 1];
                stud[j + 1] = temp;
            }
        }
    }
}

int main()
{
    struct Student stud[5];
    size_t size = sizeof(stud) / sizeof(stud[0]);
    int temp;

    system("cls");

    for (int i = 0; i < size; i++)
    {
        printf("Enter name of student: ");
        fgets(stud[i].name, 50, stdin);

        printf("Enter roll number of student: ");
        scanf("%d", &stud[i].rollNo);

        clearInputBuffer();
    }

    sortStudents(stud, size);

    for (int i = 0; i < size; i++)
    {
        printf("\nRoll no. %d\n", stud[i].rollNo);
        printf("Name: %s\n", stud[i].name);
    }

    return 0;
}