/*
    The question is generated by OpenAI GPT-4o

    Section 1: Basic Structs
    Define and Use Struct Members
    Define a struct called Car with the following members:

    brand (string of max length 50)
    model (integer for model year)
    price (float for the car price)
    Write a program to:

    Take input for these details for one car.
    Display the car’s details.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct Car
{
    char brand[50];
    int model;
    float price;
};

int main()
{
    struct Car car1;
    system("cls");
    printf("Enter name of brand: ");
    fgets(car1.brand, 50, stdin);
    printf("Enter model number: ");
    scanf("%d", &car1.model);
    printf("Enter price: Rs. ");
    scanf("%f", &car1.price);

    printf("\nName of the brand: %s", car1.brand);
    printf("The model number of the car: %d\n", car1.model);
    printf("The price of the car %.2f\n", car1.price);

    return 0;
}