/*
    The question is generated by OpenAI GPT-4o

    Modify Struct Data Using Pointers
    Using the Rectangle struct, write a program to:
    Dynamically allocate memory for a rectangle.
    Take input for its dimensions.
    Modify the dimensions using a function that takes a pointer.
    Print the updated dimensions
*/

#include <stdio.h>
#include <stdlib.h>

struct Rectangle
{
    int length, width;
};

void modifyDimensions(struct Rectangle *rect)
{

    rect->length = rect->length * 2;
    rect->width = rect->width * 2;
}

int main()
{
    struct Rectangle *rect = malloc(sizeof(struct Rectangle));
    system("cls");
    printf("Enter length: ");
    scanf("%d", &rect->length);
    printf("Enter width: ");
    scanf("%d", &rect->width);
    printf("\nOriginal\nLength: %d, Width: %d\n", rect->length, rect->width);
    modifyDimensions(rect);
    printf("\nModified\nLength: %d, Width: %d\n", rect->length, rect->width);

    free(rect);
    return 0;
}