/*
    The question is generated by OpenAI GPT-4o

    Nested Structs
    Create a struct called Student with:
    name (string of max length 50)
    rollNo (integer)
    dob (nested struct for Date of Birth with day, month, year members)
    
    Write a program to:
    Take input for 2 students, including their date of birth.
    Display their details.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct DateOfBirth
{
    int day, month, year;
};

struct Student
{
    char name[50];
    int rollNo;
    struct DateOfBirth dob;
};

void clearInputBuffer()
{
    int c;
    while ((c = getchar()) != '\n' && c != EOF)
        ; // Clear the buffer
}

int main()
{
    struct Student student[2];
    size_t size = sizeof(student) / sizeof(student[0]);

    system("cls");
    for (int i = 0; i < size; i++)
    {
        printf("Enter name of student: ");
        fgets(student[i].name, 50, stdin);
        student[i].name[strcspn(student[i].name, "\n")] = '\0';

        printf("Enter roll number: ");
        scanf("%d", &student[i].rollNo);

        printf("Enter date of birth (dd mm yy/yyyy): ");
        scanf("%d %d %d", &student[i].dob.day, &student[i].dob.month, &student[i].dob.year);

        clearInputBuffer();
    }

    for (int i = 0; i < size; i++)
    {
        printf("\nName of student: %s\n", student[i].name);
        printf("Student's roll number: %d\n", student[i].rollNo);
        printf("Date of birth of student: %d-%d-%d\n", student[i].dob.day, student[i].dob.month, student[i].dob.year);
    }

    return 0;
}