/*
    The question is generated by OpenAI GPT-4o

    Section 3: Pointers to Structs
    Dynamic Memory Allocation
    Create a program to:
    Define a struct called Book with title (string of max length 100) and pages (integer).
    Dynamically allocate memory for one book using a pointer.
    Input and display the book's details.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct Book
{
    char title[100];
    int pages;
};

void clearInputBuffer()
{
    int c;
    while ((c = getchar()) != '\n' && c != EOF)
        ;
}

int main()
{
    struct Book *book = (struct Book *)malloc(sizeof(struct Book));

    system("cls");

    printf("Enter the title of the book: ");
    fgets(book->title, 100, stdin);

    printf("Enter number of pages: ");
    scanf("%d", &book->pages);

    printf("\nTitle of the book: %s", book->title);
    printf("Number of pages in the book: %d\n", book->pages);

    clearInputBuffer();

    free(book);
    return 0;
}