/*
    The question is generated by OpenAI GPT-4o

    Pointers and Arrays of Structs
    Using the Book struct:
    Dynamically allocate memory for an array of 3 books.
    Input the details for each book.
    Display the details using pointers.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct Book
{
    int noOfPages;
    char title[50];
};

void clearInputBuffer()
{
    int c;
    while ((c = getchar()) != '\n' && c != EOF)
        ;
}

int main()
{
    // Here we made the array of 3 books dynamically allocated on the heap.
    struct Book *books = (struct Book *)malloc(3 * sizeof(struct Book));
    int numberOfBooks = 3;

    // size_t size = sizeof(books) / sizeof(books[0]); // this line is not valid for dynamically made array on heap.

    system("cls");

    for (int i = 0; i < numberOfBooks; i++)
    {
        printf("Enter title of book: ");
        fgets(books[i].title, 50, stdin);

        printf("Enter number of pages: ");
        scanf("%d", &books[i].noOfPages);
        clearInputBuffer();
    }

    for (int i = 0; i < numberOfBooks; i++)
    {
        printf("\nTitle of the book: %s", books[i].title);
        printf("Number of pages: %d\n", books[i].noOfPages);
    }

    free(books);

    return 0;
}